# Este flujo de trabajo despliega la aplicación con CodeDeploy después de que el flujo de trabajo de compilación y prueba (Java CI with Gradle) haya sido completado con éxito.

name: Java CD with CodeDeploy

# Desencadenadores: Este flujo de trabajo se activa cuando el flujo de trabajo Java CI with Gradle ha sido completado.
on:
  workflow_run:
    workflows: [Java CI with Gradle]  # Se activa cuando el flujo de trabajo Java CI with Gradle está en la lista de flujos de trabajo completados
    types: 
      - completed

# Trabajos:
jobs:
  # Trabajo "on-success":
  on-success:
    runs-on: ubuntu-20.04
    if: ${{ github.event.workflow_run.conclusion == 'success' }}  # Se ejecuta solo si el flujo de trabajo anterior fue exitoso
    steps:
      - run: echo 'The triggering workflow passed'  # Imprime un mensaje si el flujo de trabajo anterior fue exitoso

  # Trabajo "on-failure":
  on-failure:
    runs-on: ubuntu-20.04
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}  # Se ejecuta solo si el flujo de trabajo anterior falló
    steps:
      - run: echo 'The triggering workflow failed'  # Imprime un mensaje si el flujo de trabajo anterior falló
