name: Deploy

on:
  workflow_run:
    workflows: ["Java CI with Gradle"]
    types:
        - completed
jobs:
  build:
      if: ${{ github.event.workflow_run.conclusion == 'success' }}
      runs-on: ubuntu-20.04
      permissions:
        contents: read

      steps:
      -  name: r repo
         uses: actions/checkout@v4

      -  name: Credenciales 
         uses: aws-actions/configure-aws-credentials@v4.0.2
         with:
           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
           aws-region: us-east-1

      -  name: Despligue CD
         run: |
           aws deploy create-deployment \
           --application-name "jmbdweb" \
           --deployment-group-name "gcd" \
           --github-location repository=${{ github.repository }},commitId=${{ github.sha }}
       
